server:
  port: 8080

spring:
  application:
    name: productapp

  datasource:
      url: jdbc:postgresql://localhost:5432/techMarket
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
  hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: productapp-hikari
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        default_schema: product
    show-sql: false

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
